### ISSUE TITLE
Software request: Intel compiler and MKL libraries

### ISSUE THREAD

**Issue by itamblyn** [ai4d-iasc/trixie#1]

**Comment by itamblyn** [comment]
@thomsonk it would be good to get an update on the plan for this.

**Comment by fieldsa** [comment]
Short-term work-around: while the full Intel compiler is not yet on hand: in the CC stack there is an imkl version available to the public for run-time usage when programs are already compiled for MKL.
```
[fieldsa@trixie ~]$ module avail mkl
..
------------------------------ Compiler-dependent avx512 modules ------------------------------
   mkl-dnn/0.16 (ai)

---------------------------------------- Core Modules -----------------------------------------
   imkl/11.1.4.214 (math)      imkl/2017.4.239 (math)      imkl/2019.2.187 (math)
   imkl/11.3.4.258 (math,D)    imkl/2018.1.163 (math)      imkl/2019.3.199 (math)
   imkl/2017.1.132 (math)      imkl/2018.3.222 (L,math)

  Where:
   math:  Mathematical libraries / Bibliothèques mathématiques
   L:     Module is loaded
   ai:    Artificial intelligence
   D:     Default Module
   N/A:   Alias cannot be loaded with current $MODULEPATH

Use "module spider" to find all possible modules and extensions.
..

[fieldsa@trixie ~]$ module spider imkl/2018.3.222

-------------------------------------------------------------------------------------------
  imkl: imkl/2018.3.222
-------------------------------------------------------------------------------------------
    Description:
      Intel Math Kernel Library is a library of highly optimized, extensively threaded
      math routines for science, engineering, and financial applications that require
      maximum performance. Core math functions include BLAS, LAPACK, ScaLAPACK, Sparse
      Solvers, Fast Fourier Transforms, Vector Math, and more.

    Properties:
      Mathematical libraries / Bibliothèques mathématiques

    You will need to load all module(s) on any one of the lines below before the "imkl/2018.3.222" module is available to load.

      nixpkgs/16.09
..
```

**Comment by fieldsa** [comment]
Further work is in progress regarding Intel compiler licensing and this ticket will be update when details are known.

**Comment by joeydumont** [comment]
Just thought I'd mention the [tracking issue](https://github.com/ComputeCanada/software-stack/issues/18) on the CC side that would allow building software with a local Intel compiler on top of the Intel based modules of the CC software stack.

**Comment by nrcfieldsa** [comment]
It was recently discovered that since this ticket was open Intel oneAPI compiler (base toolkit + HPC toolkit) is now available for unrestricted commercial use, with an update to Intel's license terms effective Dec. 2020.

* https://www.intel.com/content/www/us/en/developer/articles/troubleshooting/oneapi-commercial-faq.html

> Published: 12/04/2020  
> Last Updated: 08/05/2021
> 
> Purchase, Renewal, and Upgrade
> Are all of the oneAPI Toolkits available for free?
> 
> Yes, all of the oneAPI Toolkits are available for free download and use for _commercial and non-commercial_ purposes.  The oneAPI Toolkits obtained for free are supported via [community forums](https://community.intel.com/t5/Software-Products/ct-p/software-products) and are public.  Only the most recent releases of the Toolkits will be made available.
> 
> Purchase
> 
> What oneAPI Toolkits are available for Commercial Support?
> 
> The Intel® oneAPI Base Toolkit is available in addition to the following combinations: Intel® oneAPI Base & HPC Toolkit, Intel® oneAPI Base & IoT Toolkit and Intel® oneAPI Base & Rendering Toolkit are available with commercial support with various use and support configuration price points.
> 
> 
> Do I need a FLEXlm license to install Intel oneAPI Toolkits or components?
> 
> A FLEXlm license is no longer needed nor used for oneAPI Commercial or Free Products.  
> 

### NRC plan for implementation:

Provided the above now meets license requirements with-out special approval necessary, the Intel compiler and toolchain can be installed on trixie cluster for general use by all researchers. Integration with Compute Canada stack  will be targeted and final terms & conditions of use reviewed by NRC. This ticket is to be discussed for approval internal to IT operations meeting, in order to proceed with the install.

**Comment by nrcfieldsa** [comment]
Intel OneAPI Base Toolkit 2022.1.2.146 install in progress.

In preparation:
 - requires libnotify installed on all nodes - complete.
 - define application install path (cluster-wide): /opt/intel/oneapi -> /gpfs/share/opt/intel/oneapi
 - license acceptance

**Comment by nrcfieldsa** [comment]
Move installed directory into shared path, update unix ownership & permissions.

**Comment by nrcfieldsa** [comment]
Generate modulefiles/ using Intel-provided modulefiles-setup.sh and add to MODULEPATH across nodes.

**Comment by nrcfieldsa** [comment]
Install Intel OneAPI HPC Toolkit 2022.1.2.117.  Regenerate modulefiles and checked that mpiifort and ifort, icc appear in PATH after module load mpi mkl icc.

**Comment by nrcfieldsa** [comment]
Ran samples from https://github.com/oneapi-src/oneAPI-samaples.git 
  - DirectProgramming/Fortran/CombinationalLogic/openmp-primes - OK
  - DirectProgramming/Fortran/DenseLinearAlgebra/vectorize-vecmatmult - OK

**Comment by nrcfieldsa** [comment]
Intel compiler is installed, two options for site-local evaluation CC CVMFS integration - as per [CC CVMS pull#6](https://github.com/ComputeCanada/easybuild-computecanada-config/pull/6):
 1. Add a separate local instance of CC CVMFS used for testing and track the feature branch;
 2. Wait for this feature branch to make it to main, in which case it should be available through existing proxy as setup.

Then the config can be checked to see if it enables the local restricted path to support icc,, ifort, mpiic, etc. binaries from `/opt/intel/oneapi` -> `/gpfs/share/opt/intel/oneapi`.

**Comment by nrcfieldsa** [comment]
@itamblyn : Can this issue be resolved now?

**Comment by itamblyn** [comment]
👍 

Thanks!
