### ISSUE TITLE
Install Unison File Synchronizer

### ISSUE THREAD

**Issue by jeixav** [ai4d-iasc/trixie#100]
Would it be possible to install [Unison](https://github.com/bcpierce00/unison) on Trixie please?

Unison helps keep files synchronized between my laptop and a server (or more generally any pair of machines). I don't think Unison is installed on Trixie, either with the Red Hat operating system or as a CVMFS module.

I have installed a copy under my `$HOME` and used it for a few months, but would prefer that it be kept up to date by Trixie system administrators.

I also emailed this request to the Client Service Centre: event S759735.

**Comment by rloveNRC** [comment]
It should now be available via `module load unison`

**Comment by jeixav** [comment]
Thank you Ryan! I confirm being able to load the Unison module.

Since I want to use Unison synchronization from my workstation to Trixie, I added `module load unison` to $HOME/.bashrc on Trixie.
