### ISSUE TITLE
SSH to Canadian University IP

### ISSUE THREAD

**Issue by itamblyn** [ai4d-iasc/trixie#11]
Outbound SSH to machines on Canadian Universities is not open (e.g. utoronto.ca)

**Comment by joeydumont** [comment]
Think of flows as a whitelist. If a lot of new flows are required, it would probably be a good idea to setup an approval workflow for these requests.

**Comment by itamblyn** [comment]
(I know, I am just posting issues so new users can see the state of things)

**Comment by itamblyn** [comment]
Closing issue and adding explaination and procedure in docs (i.e. create an issue with a specific request)
