### ISSUE TITLE
job queued and waiting for resources

### ISSUE THREAD

**Issue by drozzy** [ai4d-iasc/trixie#15]
Submitting a job like this, waiting for it for hours...
Is there something I'm doing wrong?

<img width="388" alt="Screen Shot 2020-06-28 at 2 28 37 AM" src="https://user-images.githubusercontent.com/140710/85939919-38e96f00-b8e7-11ea-8952-d0b7da706820.png">

**Comment by itamblyn** [comment]
Syntax looks wrong.

See: https://github.com/ai4d-iasc/trixie/wiki/Jobs-conda-pytorch
