### ISSUE TITLE
ability to request multiple nodes and all GPUs on each node

### ISSUE THREAD

**Issue by kryczko** [ai4d-iasc/trixie#16]
Apparently there are some issues now with -N 2 and --gres=gpu:4. This seems to request only 4 GPUs even though two nodes have been requested. There should be a way to request 8 GPUs across the two nodes.

**Comment by ddamoursNRC** [comment]
I am able to successfully allocate multiple GPUs across multiple nodes.
```bash
#!/bin/bash
#SBATCH -p JobTesting
#SBATCH -N 2
#SBATCH --gres=gpu:4
srun nvidia-smi -L > testout-smi.out
```

will generate a list of 8 GPUIDs (two sets of GPU 0-3).
Are you perhaps missing the srun within your job?

**Comment by kryczko** [comment]
This is what I have done previously, but @itamblyn had mentioned i was using resources not given to me. This was the script I was using: 
```
#!/bin/bash

# #SBATCH --partition=JobTesting
#SBATCH -A ai4d_mat_02
#SBATCH --time=2-00:00:00
#SBATCH --gres=gpu:4
#SBATCH --mem=128G
#SBATCH -N 2
export OMP_NUM_THREADS=8

NPROC_PER_NODE=4

#This command to run your pytorch script
#You will want to replace this
COMMAND=~/git/dnns/worker.py

echo Command that will be executed: $COMMAND

#We want names of master and slave nodes
MASTER=`/bin/hostname -s`
SLAVES=`scontrol show hostnames $SLURM_JOB_NODELIST | grep -v $MASTER`
#Make sure this node (MASTER) comes first
HOSTLIST="$MASTER $SLAVES"

MPORT=8013
echo Trying to use port: $MPORT
CWD=$(pwd)

echo Current working directory: $CWD

echo Here is the list of hosts: $HOSTLIST
#Launch the pytorch processes, first on master (first in $HOSTLIST) then
#on the slaves
RANK=0
for node in $HOSTLIST; do
	echo About to ssh into: $node
	echo Command that is about to be run: "ssh -q $node \"cd $CWD && export OMP_NUM_THREADS=1 && python -m torch.distributed.launch --nproc_pe
r_node=$NPROC_PER_NODE --nnodes=$SLURM_JOB_NUM_NODES --node_rank=$RANK --master_addr=$MASTER $COMMAND\" &"
	ssh -q $node "cd $CWD && export OMP_NUM_THREADS=1 && python -m torch.distributed.launch --nproc_per_node=$NPROC_PER_NODE --nnodes=$SLURM_J
OB_NUM_NODES --node_rank=$RANK --master_addr=$MASTER --master_port=8013 $COMMAND --node_rank=$RANK --gpus_per_node=4" &
	RANK=$((RANK+1))
done


wait
```

**Comment by ddamoursNRC** [comment]
Kevin, modifying your jobs to run nvidia-smi instead of launch pytorch lets me see 8 GPUs (4 on each node) so it appears to be working from a slurm perspective. 
There is no issue using srun to launch jobs across nodes allocated using sbatch.

If you are referring to the JobTesting queue instead of TrixieMain, it is fine to use for small test and debug jobs prior to submission to TrixieMain. Full job runs should be done on the TrixieMain partition. Currently there is a 2 hour job limit on the JobTesting queue but that will likely be shortened in the near future to prevent users from running full jobs on it.

**Comment by kryczko** [comment]
I am not referring to the job testing queue, that line is commented out.

**Comment by itamblyn** [comment]
@kryczko is this still a problem, or can I close the ticket?

**Comment by itamblyn** [comment]
Problem solved with srun
