### ISSUE TITLE
git clone not working with git@github.com

### ISSUE THREAD

**Issue by itamblyn** [ai4d-iasc/trixie#2]
Git clone hangs when you try to clone using git@github.com/reponame.git

It works when you switch over to https://

I am assuming this is because outbound ssh is currently disabled, but flagging it to be clear

**Comment by itamblyn** [comment]
For a workaround to this, you need to clone git repositories differently than the default.

For example, rather than using SSH

```
git clone git@github.com:ai4d-iasc/trixie.git
```

Use https

```
git clone https://github.com/ai4d-iasc/trixie.git
```
That should let you push and pull as normal

**Comment by drozzy** [comment]
Yeah except it keeps asking you for a username/password everytime.

Additionally security is much weaker if I have to provide my github password!
With git@ i just provide my public key.

**Comment by joeydumont** [comment]
Correct @itamblyn, a flow would need to be requested for outbound SSH to GitHub.

**Comment by itamblyn** [comment]
Please initiate that request.

Thanks.

**Comment by joeydumont** [comment]
Request initiated.

**Comment by drozzy** [comment]
Any update on this?

**Comment by joeydumont** [comment]
Still waiting for approval.

**Comment by joeydumont** [comment]
Should work now. Please test.

**Comment by itamblyn** [comment]
I'm marking this as resolved.
