### ISSUE TITLE
Install apex for mixed precision

### ISSUE THREAD

**Issue by drozzy** [ai4d-iasc/trixie#20]
Please install apex, for mixed precision training.
I tried but it failed since it requires compilation step.

https://github.com/NVIDIA/apex

**Comment by ddamoursNRC** [comment]
This appears to work under conda to get access to apex:

From: https://anaconda.org/conda-forge/nvidia-apex
To install this package with conda run one of the following:
```bash
conda install -c conda-forge nvidia-apex
conda install -c conda-forge/label/cf202003 nvidia-apex 
```

**Comment by drozzy** [comment]
Nevermind, it seems pytorch-lightning uses a built-in pytorch amp support:
```
When using PyTorch 1.6+ Lightning uses the native amp implementation to support 16-bit.

# turn on 16-bit
trainer = Trainer(precision=16)
```
https://pytorch-lightning.readthedocs.io/en/latest/apex.html
