### ISSUE TITLE
OLD git

### ISSUE THREAD

**Issue by drozzy** [ai4d-iasc/trixie#21]
Git version is very old: git version 1.8.3.1

Can we update it please?
The commands don't work the same way anymore.

**Comment by drozzy** [comment]
Any update on this?

**Comment by NRCGavin** [comment]
?I am looking into it along with some other repository changes.

________________________________

**Comment by ddamoursNRC** [comment]
Git has been upgrade to version 2.24

**Comment by itamblyn** [comment]
If this version is insufficient, please reopen.
