### ISSUE TITLE
disk quota exceeded

### ISSUE THREAD

**Issue by kryczko** [ai4d-iasc/trixie#24]
I hit the error: Disk quota exceeded

I was trying to copy over a large data file from another NRC machine, and the copy failed because of this error.

**Comment by NRCGavin** [comment]
?What was the destination folder?  Your Home folder?  How big was the data file?

________________________________

**Comment by kryczko** [comment]
Yes it was my home. The data file is ~80 GB.

**Comment by NRCGavin** [comment]
It appears you have exceeded your quota  soft limit of 500GB and hit the hard limit of 600GB which will prevent further transfers.


Unfortunately quota notifications still need some work.


You will either need to clean up your home folder or copy the data to an appropriate Project folder.


The project folders under /gpfs/projects/ now has a full folder structure for all identified projects.  It is recommended to put all project data in the related project folder.  There are currently no limits on project folder space.  Just a global limit of 300TB for the entire projects folder structure.

?


________________________________

**Comment by kryczko** [comment]
okay thank you, i will work in projects.

**Comment by kryczko** [comment]
could you please give me access to read/write in `/gpfs/projects/AI4D/mat-04`
