### ISSUE TITLE
transferring data from vector institute

### ISSUE THREAD

**Issue by kryczko** [ai4d-iasc/trixie#25]
I would like to transfer data from v.vectorinstitute.ai to the trixie machine. Could this be made possible?

**Comment by ddamoursNRC** [comment]
There is no direct ssh path between the two servers and so an intermediate hop through a computer who can connect to both is required.
The -3 flag on scp (not sure if Windows pscp supports this) should allow you to do this seamlessly.
```
    scp -3 user1@remote1:/home/user1/file1.txt user2@remote2:/home/user2/file1.txt
```
See: https://www.techrepublic.com/article/how-to-copy-a-file-between-two-remote-ssh-servers/

**Comment by kryczko** [comment]
I know that compute canada clusters have been white listed such that we can transfer stuff from there. Could this be done for vector as well?

**Comment by itamblyn** [comment]
What is the IP for the machine?

**Comment by itamblyn** [comment]
Bump for this

Machine is v.vectorinstitute.ca

**Comment by joeydumont** [comment]
I believe firewall changes need to be approved by the working group, or @ddamoursNRC . 

In any case, isn't Danny's solution above sufficient?

**Comment by kryczko** [comment]
I would have to ssh tunnel through 2 computers so I’m not sure how that would work.

Kevin

**Comment by joeydumont** [comment]
That shouldn't be a problem. If you're on a machine that has access to both the Vector Institute machine and to trixie, there should be a way to transfer files between them. Email me if you need a hand.

**Comment by itamblyn** [comment]
Doesn't that route the traffic through middle machine though?

**Comment by joeydumont** [comment]
I think so, yes. Is that an issue?

**Comment by kryczko** [comment]
yes, when I am trying to transfer large datasets this is not good.

**Comment by ddamoursNRC** [comment]
Assyst ticket S348676 created to track this request to SSC.

**Comment by joeydumont** [comment]
What's the IP for v.vectorinstitute.ca? nslookup doesn't find it.

**Comment by kryczko** [comment]
When I ping it I get: 142.1.174.7

**Comment by joeydumont** [comment]
Ok. We might need to request via the IP, because I can't resolve `v.vectorinstitute.ca` from NRC premises, or from my personal machine. Is that IP static?

**Comment by kryczko** [comment]
I can ping it from another NRC machine on the black network. I would think the IP would be static.

**Comment by kryczko** [comment]
also -- I am not able to reach niagara.computecanada.ca at the moment. This should have already been blacklisted.

**Comment by itamblyn** [comment]
Hey all - let's use the words "allowlist" and "blocklist" instead of "whitelist" or "blacklist" when referring to firewall terms.

**Comment by joeydumont** [comment]
I can't resolve `v.vectorinstitute.ca` from any colored network, or from my personal one, or on trixie. I can still open the request based on its IP, and you might have to use the IP to connect to it.

**Comment by kryczko** [comment]
that address is wrong. It is `v.vectorinstitute.ai`

**Comment by joeydumont** [comment]
I just now realized this by researching what the Vector Institute was. Thanks.

**Comment by thomsonk** [comment]
As update, Danny has submitted a request for SSC to implement the v.vectorinstitute.ai SSH Out flow.

**Comment by thomsonk** [comment]
I just noticed Isaac's recommendation on 'allowlist' and 'blocklist'.  I fully support that and thanks for mentioning it.

**Comment by joeydumont** [comment]
@kryczko Could you please test?

**Comment by kryczko** [comment]
Yes it works. Thanks a lot @joeydumont for getting this to work!
