### ISSUE TITLE
killing processes on a node 

### ISSUE THREAD

**Issue by kryczko** [ai4d-iasc/trixie#27]
If a node is not requested to a user via slurm, one should not be able to ssh into the node and any processes on a node should be killed. 

I am running distributed data parallel training with slurm where I can not use srun, and therefore my python commands still run after a job has been cancelled. 

I'm not entirely sure how to handle it, but a node should kill processes if it is not requested via slurm. This is what is done on compute canada machines.

**Comment by NRCGavin** [comment]
?Cn110 should accept your logins again now.


We will discuss your other suggestions internally and see what changes we can make.  It does sound like a more secure and stable approach.


Later,

Gavin

________________________________

**Comment by kryczko** [comment]
thanks Gavin!

**Comment by itamblyn** [comment]
I am not 100% sure I agree with the no ssh rule

Sometimes it is hugely helpful to login and run top just to see what is going on with a job.

I agree that processes should be killed though, e.g. which run longer than a specific time.

Maybe just restricted shell access should be allowed from users onto the nodes.

**Comment by kryczko** [comment]
You should be allowed to ssh if you request the node through Slurm. That is all.

**Comment by itamblyn** [comment]
Ah, good point

**Comment by fieldsa** [comment]
Steps have been taken to implement pam_slurm_adopt and pam_listfile.  Thus, it is now necessary to run salloc or have an existing job running on cluster, prior to ssh to compute nodes.  After the job exits, ssh login session will also be terminated. Please refer any support questions to IT Ops.

**Comment by ddamoursNRC** [comment]
As detailed by @fieldsa the issue should now be resolved. @kryczko please if resubmit jobs to confirm the correct behaviour and validate the fix.
