### ISSUE TITLE
All nodes are down

### ISSUE THREAD

**Issue by kryczko** [ai4d-iasc/trixie#29]
I notice that all nodes are down. Is there scheduled maintenance today?

**Comment by ddamoursNRC** [comment]
Unplanned outage unfortunately. Debugging and hopefully a quick fix ongoing.
Headnodes still available but no compute nodes available.

**Comment by kryczko** [comment]
Is it not possible to bring the nodes back up while you debug the slurm logs?

**Comment by ddamoursNRC** [comment]
The compute nodes are not running nor accessible. It appears to be a power issue and is being worked on.

**Comment by kryczko** [comment]
ah gotcha.

**Comment by ddamoursNRC** [comment]
Power restored and compute nodes are back up and available for jobs.
