### ISSUE TITLE
can no longer access projects directory

### ISSUE THREAD

**Issue by kryczko** [ai4d-iasc/trixie#33]
After logging in this morning I tried to access my projects directory:
```
[ryczkok@hn2 ~]$ ls -al project 
lrwxrwxrwx 1 ryczkok ryczkok 34 Jul 22 10:33 project -> /gpfs/projects/AI4D/mat-04/ryczkok
```
but I could not access this directory. My symlink was broken.

**Comment by NRCGavin** [comment]
There is some work going on with the AD groups to clean them up.  That is my first guess as to what caused this, I will take a look.  Let me know if you have this issue anywhere else as well.


________________________________

**Comment by kryczko** [comment]
I've only been working in project, so I don't see any issues elsewhere. I won't be able to run anything on the machine until i can access the project directory. All my files are there.

**Comment by NRCGavin** [comment]
?Check you access now and let me know.

________________________________

**Comment by kryczko** [comment]
Looks good.
