### ISSUE TITLE
Boost Library request

### ISSUE THREAD

**Issue by Spationaute** [ai4d-iasc/trixie#34]
Hi, I think adding the Boost library can be useful (https://www.boost.org)! It’s full of tools for C,C++ and it’s used in a lot of software. If well prepared few algorithm of the libraries automatically use MPI and run in parallel. I personally think it’s a really basic programming tool that should be available for everyone.

**Comment by joeydumont** [comment]
I fully agree with having boost on the cluster. However, as you probably have noticed, we don't currently have a proper software stack. We were trying out a method earlier this year, and some software has been installed with it, but I have reservations about installing boost with it. The main issue is that Boost is used as a dependency to other software, so if you were to build you whole application stack using the version of boost that I'm in a position to offer now, you would need to recompile your own application stack once we switch to our proper software stack.

I've started the process to get a test deployment of our software stack, but I'm not sure when it will be ready for testing.

If you don't mind rebuilding your apps once we implement our software stack, I can install boost for you. Just let me know the minimum version you need.

**Comment by Spationaute** [comment]
@joeydumont No worries I have build my own stack since all the basic tools are there! I just ask for the future!

**Comment by fieldsa** [comment]
As of this date: boost library appears in the installed CC stack. When convenient, please re-attempt to use this boost library during your build.

```
$ module avail boost

--------------------------------------- Global Aliases ----------------------------------------
   allinea-cpu -> (N/A)    arm-forge-cpu -> (N/A)
   allinea-gpu -> (N/A)    arm-forge-gpu -> (N/A)

------------------------------ Compiler-dependent avx512 modules ------------------------------
   boost/1.54.0 (t)    boost/1.65.1 (t)    boost/1.66.0 (t)    boost/1.68.0 (t,D)

-------------------------------- MPI-dependent avx512 modules ---------------------------------
   boost-mpi/1.68.0 (t)

  Where:
   t:    Tools for development / Outils de développement
   D:    Default Module
   N/A:  Alias cannot be loaded with current $MODULEPATH

$ module load boost
$ echo $LD_LIBRARY_PATH

$ echo $LIBRARY_PATH
/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx512/Compiler/gcc7.3/boost/1.68.0/lib:  [..]
```

**Comment by Spationaute** [comment]
Thank you, I'll test it when I need to compile the code again.

**Comment by Spationaute** [comment]
I confirm that BOOST Libraries from the stack are working as expected. I still have difficulties with your Armadillo configuration to fully use your stack for mathematical operation.

**Comment by Spationaute** [comment]
I'll open an issue if I need it again. I have my own little stack for now.
