### ISSUE TITLE
Library Request ARPACK

### ISSUE THREAD

**Issue by Spationaute** [ai4d-iasc/trixie#36]
Hi! I need ARPACK for Arnoldi Eigen System computation. The problem: ARPACK is a fortran library, and I can't compile it!

**Comment by joeydumont** [comment]
I've started the installation process, I'll let you know once it's deployed. Out of curiosity, why can't you compile it? `gfotrtran` is available on the system.

**Comment by Spationaute** [comment]
@joeydumont ...My own incompetence :P. I tryed f77 and f95... I did not think about gfortran... 

Thanks for the installation!

**Comment by Spationaute** [comment]
The worst I just tryed again f95 and it work... Sorry about that.

**Comment by Spationaute** [comment]
The lib will still be usefull since it seems like I don't know how to compile the shared library right...

**Comment by joeydumont** [comment]
It should be now available, and you can load it with `module load arpack-ng/3.7.0`. Let me know if it's working for you.

**Comment by Spationaute** [comment]
All is ok now.
