### ISSUE TITLE
filesystem failure

### ISSUE THREAD

**Issue by kryczko** [ai4d-iasc/trixie#37]
I just tried logging in and apparently the home directory doesn't exist:

```
-bash: cd: /home/ryczkok: Stale file handle
```

**Comment by joeydumont** [comment]
We are rebooting the GPFS nodes right now. Sorry you didn't get the notification, we sent out a notice early this morning.

**Comment by kryczko** [comment]
oh okay, no problem. Thanks for letting me know. Closing now.
