### ISSUE TITLE
issue with cn110

### ISSUE THREAD

**Issue by kryczko** [ai4d-iasc/trixie#38]
for some reason one of the GPUs on cn110 is not working as it should. Could someone please drain this node and check on it?

**Comment by NRCGavin** [comment]
?It is set to drain now.  We will investigate.

________________________________

**Comment by kryczko** [comment]
There still seems to be an issue with this node see issue #55

**Comment by kryczko** [comment]
There is still an issue with this node.

**Comment by NRCGavin** [comment]
Hopefully this time we can get HPE to replace the GPU.  I have put it into a drain state for now so it wont accept new jobs and will investigate.



________________________________

**Comment by kryczko** [comment]
thanks Gavin

**Comment by ddamoursNRC** [comment]
CN 110 has had its GPU replaced, tested  and has been put back into service.
