### ISSUE TITLE
add machine cori.nersc.gov to list of allowed connections.

### ISSUE THREAD

**Issue by kryczko** [ai4d-iasc/trixie#39]
add machine cori.nersc.gov to list of allowed connections.

**Comment by ddamoursNRC** [comment]
Kevin, I assume that you mean that you would like to allow outbound ssh connections to cori.nersc.gov from Trixie. Is that correct? Are there particular resources on cori that you need to push and/or pull?
Are you aware is anybody beside yourself have accounts on cori?

**Comment by kryczko** [comment]
Isaac would have an account on this machine as well. It is just for transferring large datasets.

**Comment by ddamoursNRC** [comment]
Request has been approved and will make its way to SSC for implementation.

**Comment by ddamoursNRC** [comment]
NRC ticket number is #S364629. Still awaiting review and implementation from SSC.

**Comment by kryczko** [comment]
Thanks @ddamoursNRC for the update.

**Comment by thomsonk** [comment]
@ddamoursNRC , has this been implemented?  Can we close this issue?

**Comment by ddamoursNRC** [comment]
Flow is confirmed as available. Marking closed.
