### ISSUE TITLE
Software request: Anaconda (full version)

### ISSUE THREAD

**Issue by itamblyn** [ai4d-iasc/trixie#4]
It can be a pain to download everything everytime with miniconda.

Full anaconda would be useful as an option

**Comment by fieldsa** [comment]
A full version of Anaconda3 was installed to base system in environment modules. (CUDA 10.1.243 release confirmed supported with Nvidia gpu drivers presently installed.)
```
[fieldsa@hn2 ~]$ module avail anaconda
------------------------------- /gpfs/share/Modules/modulefiles -------------------------------
   anaconda/3-2020.11 (L)

[fieldsa@hn2 ~]$ module load anaconda
Anaconda3-2020.11: Please don't forget to type: . activate
[fieldsa@hn2 ~]$ . activate
(base) [fieldsa@hn2 ~]$ conda list
# packages in environment at /gpfs/share/opt/anaconda/anaconda3-2020.11:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0
_libgcc_mutex             0.1                        main
alabaster                 0.7.12                     py_0
anaconda                  2020.11                  py38_0
anaconda-client           1.7.2                    py38_0
..
conda                     4.9.2            py38h578d9bd_0    conda-forge
conda-build               3.20.5                   py38_1
conda-env                 2.6.0                         1
conda-package-handling    1.7.2            py38h03888b9_0
conda-verify              3.4.2                      py_1
contextlib2               0.6.0.post1                py_0
cryptography              3.1.1            py38h1ba5d50_0
cudatoolkit               10.1.243             h6bb024c_0
..
(base) [fieldsa@hn2 ~]$ which python
/gpfs/share/opt/anaconda/anaconda3-2020.11/bin/python      
(base) [fieldsa@hn2 ~]$ echo $CONDA_PREFIX
/gpfs/share/opt/anaconda/anaconda3-2020.11
```

**Comment by fieldsa** [comment]
As a note: an alternative to using Anaconda is to use the provided CVMFS python virtualenv w/ existing installed Python packages in CC application stack. This saves on downloading w/ conda and pip where-ever possible and will allow for customization of versions in a specific venv (source ~/projects/venv/env_name/bin/activate). This approach does allow specific CUDA versions, etc. However, it may not provide all the same flexibility of Anaconda outside of Python use case. It is recommended to use the Compute Canada modules for other non-python applications where they exist to ensure maximum compatibility when loading dependency modules.

**Comment by itamblyn** [comment]
Good suggestion - please add to docs as this is a common use case.
- Isaac
