### ISSUE TITLE
failure with rsync to vector institute

### ISSUE THREAD

**Issue by kryczko** [ai4d-iasc/trixie#40]
I am trying to rsync some stuff to vector but I am receiving the error message:
```
ssh_exchange_identification: read: Connection reset by peer
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.3]
```

**Comment by fieldsa** [comment]
v.vectorinstitute.ai is reachable on port 22 from hn2 and cn101 this afternoon.
It's possible this could be a network connection failure or remote rsync daemon access restriction on the peer.

Can you reproduce this error upon connect with either a plain ssh or sftp command to the same remote address at Vector Institute using your account/pw? Is a file transfer permitted and is able to run for some time. If so, does it get a reset error after starting?

Please try again to reproduce, and email rsync command and full error ouput for us to look into it further.

**Comment by kryczko** [comment]
it is working now. So I will close this issue for now and reopen if I receive error in the future.
