### ISSUE TITLE
node cn125 not working 

### ISSUE THREAD

**Issue by kryczko** [ai4d-iasc/trixie#44]
My code is failing to execute on node cn125, it gets stuck when I try and load things into GPU memory and just hangs. My code executes fine on all other nodes.

**Comment by ddamoursNRC** [comment]
Thanks @kryczko Node has been placed in drain state and will be taken out of the queue for diagnostics. He had previously run all kind of hardware diags which came out clean and recently reimaged. Guess there is still an underlying issue to find.
