### ISSUE TITLE
failure to connect to trixie

### ISSUE THREAD

**Issue by kryczko** [ai4d-iasc/trixie#46]
I am unable to ssh in to trixie. I recieved the error:

```
Connection closed by UNKNOWN port 65535
```

**Comment by kryczko** [comment]
I am now able to login, and now the filesystem is very slow.

**Comment by Spationaute** [comment]
I have the same difficulties, Trixie is quite slow.

**Comment by ddamoursNRC** [comment]
Acknowledged and being investigated. https://github.com/ai4d-iasc/trixie/wiki/Trixie-Status

**Comment by fieldsa** [comment]
Same here - now that I am able to ping trixie - I still cannot ssh.  Intermittent - finally managed to connect via ssh.  Logging into a compute node has an authentication delay with LDAP.

$ ping trixie
PING nrc-303xxxxx.res.nrc.gc.ca (167.37.xx.xx) 56(84) bytes of data.
64 bytes from nrc-303xxxxx.res.nrc.gc.ca (167.37.xx.xx): icmp_seq=1 ttl=60 time=47.9 ms
64 bytes from nrc-303xxxxx.res.nrc.gc.ca (167.37.xx.xx): icmp_seq=2 ttl=60 time=41.9 ms
^C
[fieldsa@nrc-015xxx /]$ ssh trixie
fieldsa@167.37.xx.xx's password: 
Authentication failed.
[fieldsa@nrc-0151xxx /]$ ssh trixie
fieldsa@167.37.xx.xx's password: 
Last login: Wed Dec 16 15:05:46 2020 from 
--- nrc-303xxxxx.res.nrc.gc.ca ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 41.933/44.935/47.937/3.002 ms

Likely cause - orange network issues.

**Comment by fieldsa** [comment]
Ping times seem consistent from VPN into head node. There doesn't appear to be any packet loss at this point.

**Comment by fieldsa** [comment]
I still notice a delay at the command prompt - command completion is taking a long time. One theory is that the LDAP/krb5 port connection is not as responsive for user credentials lookup.. however, a ping doesn't show any slow-down for ICMP traffic from head-node to the directory server on orange.

**Comment by fieldsa** [comment]
Can you please perhaps further qualify that the file system is slow? Did you see any difficulty with actual file read/write to GPFS - or just in the shell? I can test as well.

**Comment by fieldsa** [comment]
It has been noted that logs indicate there is a file-system responsiveness issue. This is not related to the network/dns/ldap, but disk accesses.

**Comment by Spationaute** [comment]
The issue seems to be resolved.

**Comment by fieldsa** [comment]
At this time the storage array has an issue still and one of the four nodes is offline. This is being looked into by NRC and an existing ticket is open with the vendor regarding Infiniband time-outs on nsd01.

The jobs should be able to complete, as the storage array remains online while being worked on.

**Comment by fieldsa** [comment]
All storage array nodes back online (nsd01 has been reboot and is showing active again).
