### ISSUE TITLE
vim timing out

### ISSUE THREAD

**Issue by kryczko** [ai4d-iasc/trixie#51]
I am currently unable to use vim and I have found that the filesystem is laggy.

**Comment by fieldsa** [comment]
There doesn't appear to be any GPFS issues in the logs. However, this issue could be as a result of CVMFS access time for vim binary. An initial attempt to reproduce the file access lag, was not able to reproduce the issue.

Please state the node this was encountered on and output of command: which vim

**Comment by fieldsa** [comment]
CVMFS seems fairly responsive in a recursive file listing on hn2.

**Comment by kryczko** [comment]
It is just a vim issue, for some reason it is hanging when i try to use it. When I exit using <ctrl>-\ it then opens the file. The version of vim i am using is: /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/bin/vim

**Comment by kryczko** [comment]
found the issue, i upgraded x11 on my mac, had to restart / log out to fix issue.
