### ISSUE TITLE
communication between nodes

### ISSUE THREAD

**Issue by deeplearningmachine** [ai4d-iasc/trixie#52]
Is there any example of using two nodes from Trixie?
I keep getting the error of “RuntimeError: Address already in use” when trying to do so. Below is the script I used:

--
#!/bin/bash
#SBATCH --partition=TrixieMain  
#SBATCH --time=12:00:00
#SBATCH --gres=gpu:4
#SBATCH --nodes=2             

source activate multiplenodes

srun python -m torch.distributed.launch --nproc_per_node=4 --nnodes=2 --node_rank=0  main.py 
srun python -m torch.distributed.launch --nproc_per_node=4 --nnodes=2 --node_rank=1  main.py 
--

**Comment by SamuelLarkin** [comment]
To make this issue more useful and informative, there is a solution written as a wiki page [SLURM, pytorch distributed and Multiple Nodes](https://github.com/ai4d-iasc/trixie/wiki)

**Comment by Harry4FunResearch** [comment]
Many thanks Samuel for helping us out.

-Harry
