### ISSUE TITLE
Connection dirtily dropping at random

### ISSUE THREAD

**Issue by Spationaute** [ai4d-iasc/trixie#59]
Hi, I have recurrent random drop in my connections with trixie. The drop is dirty and leave the terminal hanging until the time out is reached. It also forbid me to reconnect for few minutes when retry connecting after the terminal hang. I have this issue for more than a week, I decide to open a tread because other members of our team signaled similar problems.

**Comment by ddamoursNRC** [comment]
@Spationaute are you still experiencing random connection drops on Trixie? Things appear to be improved but perhaps some users are still experiencing the issue.
Thanks for any feedback.

**Comment by Spationaute** [comment]
@ddamoursNRC No, it's much better! It was especially sturdy yesterday.

**Comment by ddamoursNRC** [comment]
Ok. Great. I'll close this issue and we can reopen it if the problem reoccurs.
Thanks for the quick response.
