### ISSUE TITLE
Temporary file system is too small on hn2

### ISSUE THREAD

**Issue by fieldsa** [ai4d-iasc/trixie#61]
The temporary file system: /var/tmp is presently too small for intended usage cases such as rpm package listing and searching.

It has happened quite frequently to have the yum command terminate when the file-system fills-up loading channel cache / package meta-data.

Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb12     1014M  668M  347M  66% /var/tmp

I've cleaned-up this filesystem a number of times and confirmed that a symlink doesn't help as the yum command uses the numbered directory per-user. When too many users cache are in the path, 1GB is not sufficient any longer.

**Comment by nrcfieldsa** [comment]
There is now 30GB of /tmp space post-upgrade on compute nodes and 40GB of /tmp space on trixie headnode.
