### ISSUE TITLE
Install tig on the headnode

### ISSUE THREAD

**Issue by SamuelLarkin** [ai4d-iasc/trixie#62]
Please make tig part of the default software stack on the headnode.

**Comment by fieldsa** [comment]
tig has been installed.  To make use of it:
```
[fieldsa@hn2 ~]$ module load tig; which tig
/gpfs/share/opt/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.2.0/tig-2.2.2-hqmuyn466ycwfcqhm2zywjbqniuylxqc/bin/tig
```
It only works on headnode for regular user.  It is found in the spack package tree and not in EasyBuild / CC CVMFS.  A module file has been added to point back to the spack module of longer name: tig-2.2.2-gcc-9.2.0-hqmuyn4

**Comment by fieldsa** [comment]
Please note this package requires to load: ncurses-6.2-gcc-9.2.0-2t2prwq # also from spack tree

**Comment by ddamoursNRC** [comment]
Tig installed and confirmed working.
Marking closed.
