### ISSUE TITLE
unable to log in to trixie

### ISSUE THREAD

**Issue by kryczko** [ai4d-iasc/trixie#63]
└──╼ ssh -Y trixie-ext
ssh: connect to host trixie.nrc-cnrc.gc.ca port 22: Connection refused
kex_exchange_identification: Connection closed by remote host

**Comment by NRCGavin** [comment]
?There appears to be an issue with LoginTC but I still need to confirm.   Investigating now.


________________________________
From: Kevin Ryczko ***@***.***>
Sent: 18 June 2021 08:00
To: ai4d-iasc/trixie
Cc: Subscribed
Subject: [ai4d-iasc/trixie] unable to log in to trixie (#63)


***ATTENTION*** This email originated from outside of the NRC. ***ATTENTION*** Ce courriel provient de l'extérieur du CNRC

???? ssh -Y trixie-ext
ssh: connect to host trixie.nrc-cnrc.gc.ca port 22: Connection refused
kex_exchange_identification: Connection closed by remote host

-

**Comment by Spationaute** [comment]
I was going to post the same issue!
LoginTC is not working for me.

**Comment by kryczko** [comment]
working for me now.

**Comment by Spationaute** [comment]
It's also corrected for me.

**Comment by ddamoursNRC** [comment]
Marking closed
