### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by chao1224** [ai4d-iasc/trixie#64]
Hi there,

I have some issues when logging in for the first time.
1. I am using ssh on Macbook.
2. At first, the terminal shows `Press 1 to authenticate with LoginTC Push or enter an OTP or bypass code.` I pressed 1, but didn't see any request on my LoginTC, only `No pending requests`. 
3. Then the terminal asks me to type in `Password`, which I guess is the PUB password sent in a separate email. I tried multiple times, yet all gave me `Authentication failed.`
4. Besides, if I want to do `ssh` again, the terminal will say `ssh: connect to host trixie.nrc-cnrc.gc.ca port 22: Operation timed out`, then I need to wait for couple more minutes to give a second try. Is this normal for other people?

Any help would be appreciated.

**Comment by jhickeyNRC** [comment]
Hmm, I don't see your name (Shengchao) in our list of authorized users. Could you please verify what project you are associated with?

Thank you.

**Comment by jhickeyNRC** [comment]
The user was not authorized. However, a request has been submitted to add the user to Trixie. Thus I'm marking this issue closed.
