### ISSUE TITLE
Error on login with CC CVMFS StdEnv/2018.3

### ISSUE THREAD

**Issue by fieldsa** [ai4d-iasc/trixie#69]
There is now an error on login to trixie and issues loading module files for StdEnv/2018.3.

## Impact:
The error encountered could prevent new jobs from launching and/or impact users upon new creating a new login shell.

## Symptom:
The following error message is encountered upon login (confirmed for multiple users):
```
Lmod has detected the following error:          We did not find a suitable license for Intel. If you have access to
one, you can create the file $HOME/.licenses/intel.lic with the license information. If you think you should have access to one
as part of your institution, please write to support@computecanada.ca so that we can configure it.

        Nous n'avons pas trouve de licence utilisable pour Intel. Si vous avez acces a une licence de Intel, vous pouvez creer
le fichier $HOME/.licenses/intel.lic avec l'information de la licence. Si vous pensez que vous devriez automatiquement avoir
acces a une licence via votre institution, veuillez ecrire a support@calculcanada.ca pour que nous puissions la configurer.
         
While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    intel/2018.3     /cvmfs/soft.computecanada.ca/easybuild/modules/2017/Core/intel/2018.3.lua
    StdEnv/2018.3    /cvmfs/soft.computecanada.ca/custom/modules/StdEnv/2018.3.lua
```
```
[fieldsa@hn2 ~]$ module load intel/2018.3
Lmod has detected the following error:  The following module(s) are unknown: "intel/2018.3"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "intel/2018.3"
```

The impacted module file has received a recent update from CC CVMFS mirror.
```
[fieldsa@hn2 ~]$ ls -ltr  /cvmfs/soft.computecanada.ca/easybuild/modules/2017/Core/intel/2018.3.lua
-rw-rw-r-- 1 cvmfs cvmfs 2326 Nov 18 20:53 /cvmfs/soft.computecanada.ca/easybuild/modules/2017/Core/intel/2018.3.lua
```

## Work around:
It was noted that the StdEnv/2020 still loads and allows new release intelmpi/2020.1.217 to load.  However, this may impact existing jobs and programs relying on intelmpi/2018.3 and could temporarily narrow down available software therefore.
```
[fieldsa@hn2 ~]$ module load StdEnv/2020
[fieldsa@hn2 ~]$ module list

Currently Loaded Modules:
  1) CCconfig          3) gcccore/.9.3.0  (H)      5) intel/2020.1.217 (t)   7) libfabric/1.10.1       9) StdEnv/2020 (S)
  2) gentoo/2020 (S)   4) imkl/2020.1.217 (math)   6) ucx/1.8.0              8) openmpi/4.0.3    (m)
```

**Comment by fieldsa** [comment]
Related git commit: https://github.com/ComputeCanada/easybuild-easyconfigs-installed-avx2/commit/addfe43d13a19ca8db22e11acad2d5d0bf630119 ("Built Core/intel/2018.3 with EasyBuild v4.5.0 @ build-node.computeca...")

License variable was previously defined and would be set null if nothing found.  However, now it appears that upon loading ifort - if a license file is not found it returns a fatal error notifying the user how to proceed.

Since intel/2018.3 attempts to load both Intel C and Fortran compilers:
```
depends_on("icc/.2018.3.222")
depends_on("ifort/.2018.3.222")
```

it is failing when it encounters the following new conditional.
```Diff
- prepend_path("INTEL_LICENSE_FILE", pathJoin("/cvmfs/soft.computecanada.ca/config/licenses/intel", os.getenv("CC_CLUSTER") .. ".lic"))
+ require("SitePackage")
+ local found = find_and_define_license_file("INTEL_LICENSE_FILE","intel")
+ if (not found) then
+        local error_message = [[
+        We did not find a suitable license for Intel.  If you have access to one, you can create the file $HOME/.licenses/intel.lic  with the license information. If you think you should have access to one as    part of your institution, please write to support@computecanada.ca so that we can configure it.
+        Nous n'avons pas trouve de licence utilisable pour Intel.  Si vous avez acces a une licence de Intel,  vous pouvez creer le fichier $HOME/.licenses/intel.lic  avec l'information de la licence. Si vous    pensez que vous devriez automatiquement avoir acces a une licence via votre institution, veuillez ecrire a support@calculcanada.ca pour que nous puissions la configurer.
+       ]]
+        LmodError(error_message)
+ end
```

## Analysis:
This raises the question of why trixie is presently attempting to load the Intel compiler toolchain if it later substitutes it with gcc in the StdEnv/2018.3 following login.

It may be possible to fix this issue by skipping the attempt to load any Intel compiler, and instead to make use of Intel runtime library modules only such as MKL and Intel MPI run-time loaded as a dependency of other software.

The following file by default is loading intel/2018.3 due to detecting an Intel CPU: 
```
[fieldsa@hn2 ~]$ grep -B4 -A4 intel /cvmfs/soft.computecanada.ca/custom/modules/StdEnv/2018.3.lua
local cpu_vendor_id = os.getenv("RSNT_CPU_VENDOR_ID")
if cpu_vendor_id == "amd" then
	load("gcc/7.3.0")
else
	load("intel/2018.3")  #<=====
end
load("openmpi/3.1.2")
```
```
/etc/profile.d/trixie_default.sh:10:export LMOD_SYSTEM_DEFAULT_MODULES="StdEnv/2018.3,gcccuda/.2018.3.101"
/etc/profile.d/trixie_default.sh:11:export EASYBUILD_ROBOT_PATHS=/gpfs/share/opt/easybuild/easyconfigs/:${EASYBUILD_ROBOT_PATHS}
/etc/profile.d/trixie_default.sh:12:source /cvmfs/soft.computecanada.ca/config/profile/bash.sh
```

Note: many packages in /cvmfs/soft.computecanada.ca were compiled with Intel compiler - so may need the run-time components to load properly (at least Intel MKL) which are loaded separately - so the intel/2018.3 can safely be disabled unless/until a license file exsists on trixie to support icc/ifort.

**Comment by fieldsa** [comment]
It seems the simplest workaround, is to touch an empty Intel license file in the user $HOME path:
```
[fieldsa@hn2 custom]$ touch $HOME/.licenses/intel.lic
[fieldsa@hn2 custom]$ ^Dlogout
Connection to 167.37.166.96 closed.
[fieldsa@nrc-015161r Downloads]$ ssh -X trixie
fieldsa@167.37.166.96's password: 
Last login: Mon Nov 22 20:26:59 2021 from 167.37.191.7
[..]
Please access the AI4D Wiki Page for additional information and to report issues:  
https://github.com/ai4d-iasc/trixie/wiki

Lmod is automatically replacing "intel/2018.3" with "gcc/7.3.0".
[fieldsa@hn2 ~]$ module list

Currently Loaded Modules:
  1) nixpkgs/16.09   (S)      4) StdEnv/2018.3  (S)   7) cudacore/.10.1.243  (H)
  2) imkl/2018.3.222 (math)   5) gcccore/.7.3.0 (H)   8) cuda/10.1           (t)
  3) openmpi/3.1.2   (m)      6) gcc/7.3.0      (t)   9) gcccuda/.2018.3.101 (H)
```

**Comment by fieldsa** [comment]
It seems that the CVMFS mount points are read-only, directly configured to go back through proxy host to their stratum 1/0 host to refresh the CC software tree.  Thus, even "custom" modules cannot be edit by hand to comment out the intel compiler lines for now.  So, another strategy will need to be devised for a permanent solution  Perhaps licensing the Intel compiler for trixie cluster use.

**Comment by fieldsa** [comment]
## Solution 1 (keep intel/2018.3 module):

- Users will need to temporarily implement the local work-around (or admin will find a global file path to set).

- A long-term requisition of Intel compiler license is a potential if/once approved.

## Solution 2 (update to bypass issue, no-purchase license / use gcc):

The option also exists, to switch the profile.d default environment to: StdEnv/2020 - in order to update all the software dependencies to use gentoo base incorporated into the more recent software tree built by Compute Canada. This might also provide cuda 11 by default (kernel driver backward compatible).

However, if switching immediately: it could introduce a large overhead of work for users to get their software re-compiled and ready for the new release. Instead of abruptly switching: it may be preferable to have the HPC users switch themselves and their job files up-to StdEnv/2020 and test their software, recompiling as necessary - during a long-term re-baseline to latest StdEnv.  Then at some point in the future it could be switch-over as the default for all user profiles.

https://docs.computecanada.ca/wiki/Migration_to_the_2020_standard_environment

**Comment by joeydumont** [comment]
Depending on the order of evaluation of Lmod configuration files, it might also be possible to change the default toolchain of StdEnv/2018.3 to gcc. I know a more recent version of Lmod added an option to change the config with [`/etc/lmod/lmod_config.lua`](https://lmod.readthedocs.io/en/latest/025_new.html). 

Or it might be possible to have a custom `SitePackage.lua` for trixie. From what I remember from the scripts that CC sources, it might be necessary to work with CC to allow that feature.

**Comment by fieldsa** [comment]
The lua `SitePackage.lua` configs are in a read-only mount; setting /etc/lmod/ path on cn101 didn't work; but it was possible to override the default search path by doing `export LMOD_PACKAGE_PATH="~/config/lmod` as a regular user.  However, it then causes an issue not finding the cvmfs lmod path for the rest of the lmod rc files even if I join the existing path to end (it doesn't parse path seperators (```:```)).

## Fix

There was an easier way discovered upon reading: `/cvmfs/soft.computecanada.ca/config/lmod/SitePackage_licenses.lua` file.
```Lua
    116 
    117         -- Third, look at the site-specific repository for
    118         -- $RSNT_LOCAL_LICENSE_PATH/<application>.lic
    119         local dir = os.getenv("RSNT_LOCAL_LICENSE_PATH")
    120         if (dir ~= nil) then
    121                 if (posix.stat(dir, "type") == "directory") then
    122                         local path = pathJoin(dir, application .. ".lic")
```

Locate the env variable meant to be used as a local override and implement cluster-wide profile.d fix.

```Diff
# ls -l /gpfs/share/opt/config/licenses
total 0
-rw-r--r-- 1 root root 0 Nov 22 21:47 intel.lic
# diff -bu /etc/profile.d/trixie_default.sh{.bak,}
--- /etc/profile.d/trixie_default.sh.bak        2021-06-28 16:35:40.420549299 -0400
+++ /etc/profile.d/trixie_default.sh    2021-11-22 21:52:36.096716543 -0500
@@ -6,6 +6,7 @@
 # BEGIN ANSIBLE MANAGED BLOCK
 export CC_CLUSTER=trixie
 export RSNT_LOCAL_MODULEPATHS=/gpfs/share/opt/easybuild/modules
+export RSNT_LOCAL_LICENSE_PATH=/gpfs/share/opt/config/licenses
 export RSNT_CUDA_DRIVER_VERSION="418.67"
 export LMOD_SYSTEM_DEFAULT_MODULES="StdEnv/2018.3,gcccuda/.2018.3.101"
 export EASYBUILD_ROBOT_PATHS=/gpfs/share/opt/easybuild/easyconfigs/:${EASYBUILD_ROBOT_PATHS}
[..]
```
Distributed updated profile to all cn[101-136], trixie, hn2.

Should be working now - users do not have to institute a work-around.

**Comment by fieldsa** [comment]
This issue is now resolved.

**Comment by fieldsa** [comment]
closing ticket.

**Comment by fieldsa** [comment]
closing ticket.

**Comment by ddamoursNRC** [comment]
Marking as closed.
