### ISSUE TITLE
Many password prompts in the process

### ISSUE THREAD

**Issue by drozzy** [ai4d-iasc/trixie#7]
I am not going to post full instructions here because of sensitive information, but the gist is right now it takes a bunch of password prompts to get into trixi:

Reguest login (one password entry)
Ssh to another machine (another password entry)
Login to Trixi (and another one)

I'd much rather have one strong long password, than 10 weak ones.

**Comment by ddamoursNRC** [comment]
Logging into the VPN allows direct access (yes the VPN requires a password).
Work is ongoing to make it available externally so the two middle steps wouldn't be required but two factor authentication will be in place for external connections.

**Comment by drozzy** [comment]
It's also pretty slow to resume work.

For example if I close my laptop it closes my connection... I can't just resume where I left off.

**Comment by drozzy** [comment]
Example - one line I'm on remote machine, the next line I'm back on my laptop...


<img width="791" alt="Screen Shot 2020-06-21 at 2 16 49 AM" src="https://user-images.githubusercontent.com/140710/85218128-45a91880-b365-11ea-9d91-85e1c8ada95f.png">

**Comment by Spationaute** [comment]
You can use ssh-agent with keys to reduce the number of password, it allows you to skip bastion password. When configured with ControlMaster and ProxyJump, to connection protocol is reduced to the LoginTC auth and one password.

**Comment by ddamoursNRC** [comment]
From the NRC network (black or orange networks), getting a prompt on Trixie only requires one password or an SSH key to be installed. Streamlining passwords for local login and VPN access is out of scope of Trixie.
For external collaborators, there are two username and a second factor but that has been streamlined to one password and second factor using LoginTC using the ProxyJump and ControlMaster options.
Can we mark this as closed?

**Comment by itamblyn** [comment]
Network state has changed enough this issue is stale. Closing for now.
