### ISSUE TITLE
error when trying to run Pytorch code

### ISSUE THREAD

**Issue by Harry4FunResearch** [ai4d-iasc/trixie#70]
I got the following error when trying to execute my pytorch code. Any suggestions?

-----
Lmod has detected the following error: The following module(s) are unknown:
"miniconda3-4.7.12.1-gcc-9.2.0-j2idqxp"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "miniconda3-4.7.12.1-gcc-9.2.0-j2idqxp"

Also make sure that all modulefiles written in TCL start with the string
#%Module

/var/spool/slurm/d/job61253/slurm_script: line 37: activate: No such file or directory
Traceback (most recent call last):
  File "run.py", line 12, in <module>
    import torch
ImportError: No module named torch

**Comment by Harry4FunResearch** [comment]
Problem solved. The solution was provided by Danny D'Amours. Thanks a lot Danny!!
--
replacing 
module load miniconda3-4.7.12.1-gcc-9.2.0-j2idqxp 
with 
module load spack "miniconda3-4.7.12.1-gcc-9.2.0-j2idqxp"
--

**Comment by fieldsa** [comment]
Can you please specify which compute node and commands were used when the module load error occurred?  Is this in a batch file or on an interactive shell (command-line).

Otherwise, it's hard to understand why you get this error message (when not specifying spack first - if it worked before)

**Comment by Harry4FunResearch** [comment]
It was in a batch file when loading the module using the following:
module load miniconda3-4.7.12.1-gcc-9.2.0-j2idqxp

It happened to three different compute nodes I tested.

**Comment by fieldsa** [comment]
OK.  The cause was tracked down - the lines are reverted on compute nodes to use spack by default.
