### ISSUE TITLE
unable to ssh in

### ISSUE THREAD

**Issue by kryczko** [ai4d-iasc/trixie#72]
Hi all, I am trying to ssh-in, and I am getting the following error

```
┌─[kryczko@boltzmann]─[~]
└──╼ ssh -Y trixie-ext
ssh: connect to host trixie.nrc-cnrc.gc.ca port 22: Operation timed out
kex_exchange_identification: Connection closed by remote host
```

**Comment by ddamoursNRC** [comment]
Thanks for reporting the issue Kevin. Indeed, the bastion host to reach Trixie is currently experiencing issue with ssh. Investigating the root cause and working to get it back up quickly.

**Comment by kryczko** [comment]
Thank you!!

**Comment by NRCGavin** [comment]
Please try again and let me know if you have access now.

?

________________________________

**Comment by kryczko** [comment]
Yes it is working now -- however i am no longer receiving notifications from LoginTC from my phone. I'm not sure if this is an issue with my phone.

**Comment by Spationaute** [comment]
@kryczko I had the same difficulties with ssh, now it's connect and I have no issues with LoginTC.

**Comment by kryczko** [comment]
I'll look into issues with my phone and create a new issue as needed.
