### ISSUE TITLE
conda pytorch wiki guide outdated

### ISSUE THREAD

**Issue by esmab** [ai4d-iasc/trixie#73]
The wiki page [Jobs Conda Pytorch](https://github.com/ai4d-iasc/trixie/wiki/Jobs-conda-pytorch) has this line that currently only installs cpu versions of pytorch:

```
# install pytorch dependencies via conda
conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
```

Adding versions to pytorch and torchvision solves the issue:
```
conda install pytorch==1.7.1 torchvision==0.8.2 cudatoolkit=10.1 -c pytorch
```

Changing this would save newcomers like me some time, since once the cpu versions are installed, it takes some googling to convince conda to replace them with the cuda versions.

**Comment by ddamoursNRC** [comment]
Thanks Esma. Your update is appreciated and has been applied to the wiki example page.
