### ISSUE TITLE
`jq` with compiled with ONIGURUMA

### ISSUE THREAD

**Issue by SamuelLarkin** [ai4d-iasc/trixie#76]
Please add a version of `jq` that is compiled with `ONIGURUMA`.

Error message that I'm currently getting.
```
jq was compiled without ONIGURUMA regex libary. match/test/sub and related functions are not available.
```

**Comment by nrcfieldsa** [comment]
Installation of jq with ONIGURUMA support to trixie. Please confirm if works ok:
```
module load jq
```

Note: the main release of jq is found in Compute Canada base.  This release of jq is standalone from spack and thus must be loaded separately

**Comment by SamuelLarkin** [comment]
`jq` is now using `ONIGURUMA` as I'm able to use the `test` command.

```bash
jq 'select(.fr | test("<[^>]+>"))' test.jsonl
```
```
{
  "en": "<Affiliation DbId=\"252885\" Type=\"2\">Mr. Jasraj Singh Hallan (Calgary Forest Lawn, CPC)</Affiliation>:",
  "fr": "<Affiliation DbId=\"252885\" Type=\"2\">M. Jasraj Singh Hallan (Calgary Forest Lawn, PCC)</Affiliation>:",
  "id": "House/House/432/Debates/121/HAN121 1356",
  "tag": "PersonSpeaking",
  "language": "English"
}
```

# Info
[Regular expressions (PCRE)](https://stedolan.github.io/jq/manual/v1.6/)
jq uses the Oniguruma regular expression library.
The jq regex filters are defined so that they can be used using one of these patterns:
```
STRING | FILTER( REGEX )
```
where: STRING, REGEX and FLAGS are jq strings and subject to jq string interpolation; REGEX, after string interpolation, should be a valid PCRE regex; * FILTER is one of test, match, or capture, as described below.
