### ISSUE TITLE
tmux missing

### ISSUE THREAD

**Issue by drozzy** [ai4d-iasc/trixie#8]
There is no tmux...
If I get disconnected I loose my session completely.

**Comment by joeydumont** [comment]
`screen` should be installed, though.

**Comment by drozzy** [comment]
I've never used screen :-(
Can't we have tmux? It's much better from what I've read.

**Comment by joeydumont** [comment]
`tmux` should now be installed on the login nodes. Note that the software stack is under heavy development, and might change.

@itamblyn, please close this issue.

**Comment by drozzy** [comment]
Thank you!
