### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by chao1224** [ai4d-iasc/trixie#80]
Hi there,

I started to get the following connection issue after typing `ssh admin.[first name].[last name]@trixie.res.nrc.gc.ca`:
```
ssh: connect to host trixie.res.nrc.gc.ca port 22: Connection timed out
```

This has shown up since two days ago. Any help would be appreciated.

**Comment by ddamoursNRC** [comment]
There appeared to be a connectivity issues likely caused by power issues in Ottawa during this weekend's storm. Everything appears to be back online and available again.
Sorry for the inconvenience.
