### ISSUE TITLE
pip: command not found...

### ISSUE THREAD

**Issue by Harry4FunResearch** [ai4d-iasc/trixie#82]
Tried to use pip install, but got the following error:

bash: pip: command not found...

Anyone has similar issue here?

**Comment by jhickeyNRC** [comment]
I looked at the trixie system and although `pip` is not available, you can try the command `pip3`. If you want to use pip as a command, you can set an alias in your .bashrc file as follows

`​alias pip=pip3`

Please let me know if this fixes your issue.


​

**Comment by Harry4FunResearch** [comment]
Yes, it works perfectly. Thanks!
